import type { VoiceModel } from "@saas/types";

export const PRESET_VOICES: readonly VoiceModel[] = [
  {
    id: "voice-aurora",
    name: "Aurora Vance",
    gender: "female",
    category: "narrative",
    language: "en-US",
    languageName: "English (United States)",
    previewAudioUrl: "/audio/previews/aurora.mp3",
    avatarUrl: "/avatars/aurora.webp",
    supportedEmotions: ["neutral", "empathetic", "whispering", "dramatic"],
    isPremium: true,
    tags: ["Warm", "Audiobook", "Cinematic", "Deep"],
  },
  {
    id: "voice-marcus",
    name: "Marcus Sterling",
    gender: "male",
    category: "commercial",
    language: "en-GB",
    languageName: "English (United Kingdom)",
    previewAudioUrl: "/audio/previews/marcus.mp3",
    avatarUrl: "/avatars/marcus.webp",
    supportedEmotions: ["neutral", "authoritative", "dramatic"],
    isPremium: true,
    tags: ["British", "Executive", "Documentary", "Crisp"],
  },
  {
    id: "voice-elena",
    name: "Elena Rostova",
    gender: "female",
    category: "conversational",
    language: "en-US",
    languageName: "English (United States)",
    previewAudioUrl: "/audio/previews/elena.mp3",
    avatarUrl: "/avatars/elena.webp",
    supportedEmotions: ["neutral", "cheerful", "excited", "empathetic"],
    isPremium: false,
    tags: ["Friendly", "Podcast", "Upbeat", "Natural"],
  },
  {
    id: "voice-kai",
    name: "Kai Takahashi",
    gender: "male",
    category: "commercial",
    language: "en-US",
    languageName: "English (United States)",
    previewAudioUrl: "/audio/previews/kai.mp3",
    avatarUrl: "/avatars/kai.webp",
    supportedEmotions: ["neutral", "cheerful", "excited"],
    isPremium: false,
    tags: ["Youthful", "Promo", "Tech", "Energetic"],
  },
  {
    id: "voice-seraphina",
    name: "Seraphina Lin",
    gender: "female",
    category: "meditation",
    language: "en-AU",
    languageName: "English (Australia)",
    previewAudioUrl: "/audio/previews/seraphina.mp3",
    avatarUrl: "/avatars/seraphina.webp",
    supportedEmotions: ["neutral", "empathetic", "whispering"],
    isPremium: true,
    tags: ["Calm", "Mindfulness", "Soft", "Breathy"],
  },
] as const;

export const DEFAULT_VOICE_ID = "voice-aurora";

export const DEFAULT_VOICE_SETTINGS = {
  stability: 0.75,
  similarityBoost: 0.85,
  style: 0.45,
  speed: 1.0,
  pitch: 0,
} as const;
